### ISSUE TITLE
Publish new version?

### ISSUE THREAD

**Issue by filiph** [miquelbeltran/flutter95#13]
I noticed that https://github.com/miquelbeltran/flutter95/blob/master/lib/src/menu95.dart#L66 has `String label` (which is correct) but the version on pub.dev has `T label` (incorrect).

Would you be able to release a new minor version? I also have a PR that upgrades to Dart 3: https://github.com/miquelbeltran/flutter95/pull/12. And maybe I'll add another one soon-ish.

**Comment by miquelbeltran** [comment]
Thanks a lot for the PRs! I will do a release once the PRs are merged.

**Comment by miquelbeltran** [comment]
Package 1.1.0 has been published.
