### ISSUE TITLE
Toolbar is too low on iPhone 11 Pro Max

### ISSUE THREAD

**Issue by transmissions11** [miquelbeltran/flutter95#2]
Hey!

I love this project, and have been trying out the example code, but I noticed that on an iPhone 11 Pro Max, the toolbar looks a little off.

On devices like the iPhone 8, the toolbar looks great, but running the example on an iPhone 11 Pro Max applies too much padding to the menu bar, maybe due to the notch?

![ScreenShot- 173](https://user-images.githubusercontent.com/26209401/85768834-4972cd00-b6ce-11ea-939c-8eebd69d47a4.png)

Thanks for making this awesome project!

**Comment by miquelbeltran** [comment]
Thanks for noticing! definitely the project needs more testing :) I will investigate and see why.

**Comment by transmissions11** [comment]
@miquelbeltran Awesome thanks so much!
